# Copyright (c) 2024 Project CHIP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build_overrides/chip.gni")
import("//build_overrides/efr32_sdk.gni")
import("${silabs_sdk_build_root}/silabs_board.gni")

declare_args() {
  sl_use_provision_channel = false
}

if (wifi_soc) {
  import("${silabs_sdk_build_root}/SiWx917_sdk.gni")
} else {
  import("${silabs_sdk_build_root}/efr32_sdk.gni")
}

# Separate import since matter_support_root is defined in the EFR32/SiWx917 SDK imports.
import("${matter_support_root}/provision/args.gni")
config("storage-config") {
  include_dirs = [ ".." ]
}

source_set("storage") {
  sources = [
    "ProvisionCrypto.h",
    "ProvisionStorageReader.h",
    "ProvisionStorageReaderCommon.cpp",
  ]

  if (wifi_soc) {
    if (sl_si91x_crypto_flavor != "psa") {
      sources += [ "ProvisionCryptoMbed.cpp" ]
    } else {
      sources += [ "ProvisionCryptoPSA.cpp" ]
    }
  } else {
    sources += [ "ProvisionCryptoPSA.cpp" ]
  }

  if (use_provision_flash_storage) {
    sources += [
      "flash/ProvisionStorageFlash.cpp",
      "flash/ProvisionStorageFlash.h",
      "flash/ProvisionStorageReader.cpp",
    ]
  } else {
    sources += [ "default/ProvisionStorageReader.cpp" ]
  }

  if (sl_use_provision_channel) {
    sources += [
      "ProvisionStorageCustom.cpp",
      "ProvisionStorageWriter.h",
      "ProvisionTransport.h",
    ]
    if (!use_provision_flash_storage) {
      sources += [ "default/ProvisionStorageWriter.cpp" ]
    } else {
      sources += [ "flash/ProvisionStorageWriter.cpp" ]
    }
    if (wifi_soc) {
      sources += [ "ProvisionTransportSi917BLE.cpp" ]
    } else {
      sources += [ "ProvisionTransportEFR32BLE.cpp" ]
    }
  }

  if (sl_use_provision_channel) {
    if (wifi_soc) {
      _provision_abi = "m4-softfp"
    } else {
      _provision_abi = "m33-hard"
    }

    if (is_clang) {
      libs =
          [ "${sl_provision_root}/libs/libProvision-${_provision_abi}-clang.a" ]
    } else {
      libs = [ "${sl_provision_root}/libs/libProvision-${_provision_abi}.a" ]
    }
  }

  deps = [ "${chip_root}/src/lib" ]

  public_deps = [
    "${chip_root}/src/app:test-event-trigger",
    "${sl_provision_root}:headers",
  ]

  public_configs = [ ":storage-config" ]
  if (sl_enable_test_event_trigger) {
    public_configs += [ "${chip_root}/examples/platform/silabs/test-event-trigger:test-event-trigger-config" ]
  }
}
