#ifdef SL_SI91X_ACX_MODULE
#define SI91X_REGION_CODE IGNORE_REGION
#else
#define SI91X_REGION_CODE US
#endif

#if defined(SLI_SI91X_ENABLE_BLE) && SLI_SI91X_ENABLE_BLE
#define SI91X_COEX_MODE SL_SI91X_WLAN_BLE_MODE
#define SI91X_BT_FEATURE_BITMAP_VALUE \
  (RSI_BT_FEATURE_BITMAP              \
   IF_RSI_BT_GATT_ON_CLASSIC(| SL_SI91X_BT_ATT_OVER_CLASSIC_ACL))
#else
#define SI91X_COEX_MODE SL_SI91X_WLAN_ONLY_MODE
#define SI91X_BT_FEATURE_BITMAP_VALUE 0
#endif

#if defined(SL_MATTER_ENABLE_DUAL_STACK) && SL_MATTER_ENABLE_DUAL_STACK
#define SI91X_TCP_IP_FEATURE_BITMAP                                      \
  (SL_SI91X_TCP_IP_FEAT_DHCPV4_CLIENT | SL_SI91X_TCP_IP_FEAT_DNS_CLIENT \
   | SL_SI91X_TCP_IP_FEAT_SSL | SL_SI91X_TCP_IP_FEAT_ICMP               \
   | SL_SI91X_TCP_IP_FEAT_EXTENSION_VALID                               \
   IF_SLI_SI91X_ENABLE_IPV6(| SL_SI91X_TCP_IP_FEAT_DHCPV6_CLIENT        \
                            | SL_SI91X_TCP_IP_FEAT_IPV6))
#else
#define SI91X_TCP_IP_FEATURE_BITMAP (SL_SI91X_TCP_IP_FEAT_BYPASS)
#endif

#define SI91X_FEATURE_BITMAP                         \
  (SL_SI91X_FEAT_SECURITY_OPEN | SL_SI91X_FEAT_AGGREGATION \
   IF_NOT_SLI_SI91X_MCU_INTERFACE(                   \
     | SL_SI91X_FEAT_ULP_GPIO_BASED_HANDSHAKE        \
     | SL_SI91X_FEAT_DEV_TO_HOST_ULP_GPIO_1))

#define SI91X_EXT_CUSTOM_FEATURE_BITMAP                         \
  (SL_SI91X_EXT_FEAT_SSL_VERSIONS_SUPPORT                       \
   | SL_SI91X_EXT_FEAT_LOW_POWER_MODE                           \
   | SL_SI91X_EXT_FEAT_IEEE_80211W                              \
   | SL_SI91X_EXT_FEAT_XTAL_CLK_ENABLE(USE_BYPASS_CLOCK == 1 ? 2 : 1) \
   | SI91X_RAM_LEVEL                                             \
   | SI91X_FRONT_END_SWITCH                                      \
   IF_SLI_SI91X_ENABLE_BLE(| SL_SI91X_EXT_FEAT_BT_CUSTOM_FEAT_ENABLE))

#ifdef SLI_SI91X_MCU_INTERFACE
#define SI91X_RAM_LEVEL SL_SI91X_RAM_LEVEL_NWP_BASIC_MCU_ADV
#else
#define SI91X_RAM_LEVEL SL_SI91X_RAM_LEVEL_NWP_BASIC
#endif

#if SL_SI91X_ACX_MODULE == 1
#define SI91X_FRONT_END_SWITCH SL_SI91X_EXT_FEAT_FRONT_END_INTERNAL_SWITCH
#else
#define SI91X_FRONT_END_SWITCH SL_SI91X_EXT_FEAT_FRONT_END_SWITCH_PINS_ULP_GPIO_4_5_0
#endif

const sl_wifi_device_configuration_t config = {
  .boot_option = LOAD_NWP_FW,
  .mac_address = NULL,
  .band        = SL_SI91X_WIFI_BAND_2_4GHZ,
  .region_code = SI91X_REGION_CODE,

  .boot_config = {
    .oper_mode                  = SL_SI91X_CLIENT_MODE,
    .coex_mode                  = SI91X_COEX_MODE,
    .feature_bit_map            = SI91X_FEATURE_BITMAP,
    .tcp_ip_feature_bit_map     = SI91X_TCP_IP_FEATURE_BITMAP,
    .custom_feature_bit_map     = SL_SI91X_CUSTOM_FEAT_EXTENTION_VALID,
    .ext_custom_feature_bit_map = SI91X_EXT_CUSTOM_FEATURE_BITMAP,
    .bt_feature_bit_map         = SI91X_BT_FEATURE_BITMAP_VALUE,

    .ext_tcp_ip_feature_bit_map =
      (SL_SI91X_CONFIG_FEAT_EXTENTION_VALID
#if defined(SL_MATTER_ENABLE_DUAL_STACK) && SL_MATTER_ENABLE_DUAL_STACK
       | SL_SI91X_EXT_TCP_IP_DUAL_MODE_ENABLE
       | SL_SI91X_EXT_TCP_IP_FEAT_SSL_MEMORY_CLOUD
#endif
#if defined(SLI_SI91X_ENABLE_BLE) && SLI_SI91X_ENABLE_BLE
       | RSI_EXT_TCPIP_FEATURE_BITMAP
#endif
#ifdef RSI_PROCESS_MAX_RX_DATA
       | SL_SI91X_EXT_TCP_MAX_RECV_LENGTH
#endif
      ),

#if defined(SLI_SI91X_ENABLE_BLE) && SLI_SI91X_ENABLE_BLE
    .ble_feature_bit_map =
      (SL_SI91X_BLE_MAX_NBR_PERIPHERALS(RSI_BLE_MAX_NBR_PERIPHERALS)
       | SL_SI91X_BLE_MAX_NBR_CENTRALS(RSI_BLE_MAX_NBR_CENTRALS)
       | SL_SI91X_BLE_MAX_NBR_ATT_SERV(RSI_BLE_MAX_NBR_ATT_SERV)
       | SL_SI91X_BLE_MAX_NBR_ATT_REC(RSI_BLE_MAX_NBR_ATT_REC)
       | SL_SI91X_FEAT_BLE_CUSTOM_FEAT_EXTENTION_VALID
       | SL_SI91X_BLE_PWR_INX(RSI_BLE_PWR_INX)
       | SL_SI91X_BLE_PWR_SAVE_OPTIONS(RSI_BLE_PWR_SAVE_OPTIONS)
       | SL_SI91X_916_BLE_COMPATIBLE_FEAT_ENABLE
#if RSI_BLE_GATT_ASYNC_ENABLE
       | SL_SI91X_BLE_GATT_ASYNC_ENABLE
#endif
      ),

    .ble_ext_feature_bit_map =
      (SL_SI91X_BLE_NUM_CONN_EVENTS(RSI_BLE_NUM_CONN_EVENTS)
       | SL_SI91X_BLE_NUM_REC_BYTES(RSI_BLE_NUM_REC_BYTES)
#if RSI_BLE_INDICATE_CONFIRMATION_FROM_HOST
       | SL_SI91X_BLE_INDICATE_CONFIRMATION_FROM_HOST
#endif
#if RSI_BLE_MTU_EXCHANGE_FROM_HOST
       | SL_SI91X_BLE_MTU_EXCHANGE_FROM_HOST
#endif
#if RSI_BLE_SET_SCAN_RESP_DATA_FROM_HOST
       | SL_SI91X_BLE_SET_SCAN_RESP_DATA_FROM_HOST
#endif
#if RSI_BLE_DISABLE_CODED_PHY_FROM_HOST
       | SL_SI91X_BLE_DISABLE_CODED_PHY_FROM_HOST
#endif
#if BLE_SIMPLE_GATT
       | SL_SI91X_BLE_GATT_INIT
#endif
      ),
#else
    .ble_feature_bit_map     = 0,
    .ble_ext_feature_bit_map = 0,
#endif

    .config_feature_bit_map =
      (SL_SI91X_FEAT_SLEEP_GPIO_SEL_BITMAP | SL_SI91X_ENABLE_ENHANCED_MAX_PSP),
  },
};