name: Build Lighting App

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
            - "release_*"

jobs:
    build:
        name: Build Lighting-App variations
        uses: ./.github/workflows/silabs-common-build.yaml
        with:
            example-app: "lighting-app"
            output-directory: "./out/lighting-app"
