name: Build Lock App

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
            - "release_*"

jobs:
    build:
        name: Build Lock-App variations
        uses: ./.github/workflows/silabs-common-build.yaml
        with:
            example-app: "lock-app"
            output-directory: "./out/lock-app"
