name: Rebase CSA

on: 
  push:
  workflow_dispatch:
       
jobs:
  rebase_csa:
    name: Rebase CSA  
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps: 

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add CSA Upstream 
        run: git remote add upstream https://github.com/project-chip/connectedhomeip.git

      - name: Configure git identity
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email ${{ github.actor }}@users.noreply.github.com

      - name: Fetch and Rebase
        run: |
          git fetch upstream 
          git rebase upstream/master 
        continue-on-error: true

      - name: Delete all CSA workflows from rebase and continue the rebase if there was a merge conflict
        run: |
          find ./.github -mindepth 1 ! -name workflows  ! -name silabs_workflow.yaml -exec git rm -rf {} \;
          git -c core.editor=true rebase --continue
        continue-on-error: true
      - run: git push -f