name: SL Labeler

on:
  pull_request:
    branches:
      - main
      - release_*
    types: [opened, edited, synchronize, reopened]

jobs:
  check-sl-prefix:
    name: Check SL Prefix and Apply Labels
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'silabs-matter-ci-bot' }}
    steps:
      - name: Generate token for the workflow
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.SILABSSW_MATTER_CI_BOT_APP_ID }}
          private-key: ${{ secrets.SILABSSW_MATTER_CI_BOT_APP_PRIVATE_KEY }}
      
      - name: Mask the generated token
        run: echo "::add-mask::${{ steps.generate_token.outputs.token }}"

      - name: Check PR title for SL prefix and apply labels
        uses: actions/github-script@v8
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            const prTitle = context.payload.pull_request.title;
            const prNumber = context.payload.pull_request.number;
            
            console.log(`Checking PR title: "${prTitle}"`);
            
            // Define the valid prefixes and their corresponding labels
            const prefixMapping = {
              '[SL-ONLY]': 'sl-only',
              '[SL-TEMP]': 'sl-temp',
              '[SL-UP]': 'sl-up'
            };
            
            const allSlLabels = Object.values(prefixMapping);
            
            // First, get current labels to remove any existing SL labels
            console.log('Getting current PR labels...');
            const { data: currentLabels } = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber
            });
            
            // Remove any existing SL labels to ensure only one at a time
            const existingSlLabels = currentLabels.filter(label => allSlLabels.includes(label.name));
            if (existingSlLabels.length > 0) {
              console.log(`Removing existing SL labels: ${existingSlLabels.map(l => l.name).join(', ')}`);
              for (const label of existingSlLabels) {
                try {
                  await github.rest.issues.removeLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: prNumber,
                    name: label.name
                  });
                  console.log(`Removed label: ${label.name}`);
                } catch (error) {
                  console.log(`Warning: Could not remove label '${label.name}': ${error.message}`);
                }
              }
            }
            
            // Check if the title starts with any of the valid prefixes
            let foundPrefix = null;
            let labelToApply = null;
            
            for (const [prefix, label] of Object.entries(prefixMapping)) {
              if (prTitle.startsWith(prefix)) {
                foundPrefix = prefix;
                labelToApply = label;
                break;
              }
            }
            
            if (!foundPrefix) {
              // No valid prefix found - fail the workflow
              const validPrefixes = Object.keys(prefixMapping).join(', ');
              const errorMessage = `❌ PR title prefix is missing. Please add one of the following prefixes to your PR title: ${validPrefixes}`;
              
              console.log(errorMessage);
              
              // Add a comment to the PR explaining the issue
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: errorMessage
              });
              
              // Fail the workflow
              throw new Error(`PR title must start with one of: ${validPrefixes}`);
            } else {
              // Valid prefix found - apply the corresponding label
              console.log(`✅ Found valid prefix: ${foundPrefix}, applying label: ${labelToApply}`);
              
              try {
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: prNumber,
                  labels: [labelToApply]
                });
                
                console.log(`Label '${labelToApply}' applied successfully`);
              } catch (error) {
                console.log(`Warning: Could not apply label '${labelToApply}': ${error.message}`);
                // Continue without failing - the prefix check passed
              }
            }